var data = [
"The boss won’t go for that.",
"The lawyers won’t go for that.",
"The accountants won’t go for that.",
"The client won’t go for that.",
"The salespeople won’t go for that.",
"The investors won’t go for that.",
"So and so won’t like it.",
"It’s not us.",
"It won’t fit into our system.",
"We’re not ready for that yet.",
"I don’t think it will work.",
"I don’t understand.",
"Do you understand?",
"Will anyone understand?",
"What will they think of next?",
"It’s politically incorrect.",
"It’s too complicated.",
"It’s too late for that now.",
"It’s too expensive.",
"We’ll lose money.",
"What!?",
"Who says?",
"Nobody will want that.",
"Where are you coming from?",
"It can’t be done.",
"Have the committee review it.",
"Let’s do more research.",
"Let’s take a vote on it.",
"Let’s play devil’s advocate.",
"I’ve never heard of such a thing.",
"We’ve already tried that.",
"That’s been done before.",
"It’s not how we do things here.",
"We’ve never done anything like that.",
"We’ll get back to you.",
"That’s a subject for another meeting.",
"It creates more problems than it solves.",
"Sounds like too many problems.",
"That only solves some of the problems.",
"That’s going to cause problems.",
"Here we go again.",
"That’s unique, but . . .",
"Very interesting, but . . .",
"I understand, but . . .",
"I love it, but . . .",
"Great idea, but . . .",
"Yes, but . . .",
"Sounds simple, but . . .",
"But . . .",
"It’s just not for us.",
"Try again.",
"That sucks.",
"Needs more pizzazz!",
"I don’t like it.",
"Have you thought it through?",
"It won’t sell.",
"Maybe next time.",
"Another day.",
"What are people going to say?",
"People will think we’re nuts!",
"That’s BS.",
"Be realistic.",
"How about this instead?",
"Get a grip!",
"Are you serious?",
"That turns me off!",
"The client is too liberal for that.",
"The client is too conservative for that.",
"What else do you have?",
"So!",
"So what?",
"Oh . . .",
"Oh?",
"Oh, really!",
"Get real, it’s not feasible.",
"Sounds crazy!",
"Nobody does that.",
"Are you kidding me?",
"That’s too off the wall.",
"You can’t argue with success.",
"You can’t fight City Hall.",
"We don’t have time to do it.",
"Let’s not reach beyond our grasp.",
"We’re overextended already.",
"Let’s wait ‘til we see the numbers.",
"You’re proposing what?",
"Let’s not rock the boat.",
". . . .",
"HAHAH",
"Where did that come from?",
"I’ve got a better idea.",
"Hey, there’s a recession going on.",
"We’ve never done anything like that.",
"The press will kill us.",
"That’s not your decision to make.",
"We’ll step on too many toes.",
"Just leave it to me; I’ll take care of it.",
"You could lose your job for that . . .",
];